source 'https://rubygems.org'
source 'http://gems.bstar.wido.me'

gem 'rails', '4.0.0'
gem 'pg', '~> 0.15'
gem 'rails-i18n', '~> 4.0.0.pre'

gem 'simple_form', '~> 3.0.0.rc'
gem 'kaminari', '~> 0.14.1'
gem 'bootstrap-kaminari-views', '~> 0.0.2'
gem 'faye', '~> 1.0.0'
gem 'httparty', "~> 0.9.0"


# Assets
gem 'jquery-rails', '~> 3.0.2'
gem 'jquery-ui-rails', '~> 4.0.2'
gem 'turbolinks', '~> 1.2.0'
gem 'jquery-turbolinks', '~> 1.0.0'

gem 'compass-rails', git: 'https://github.com/Compass/compass-rails.git', branch: 'rails4-hack'
gem 'bootstrap-sass', '~> 2.3.1'
gem 'font-awesome-sass-rails', '~> 3.0.2.2'

gem 'sass-rails', '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer', platforms: :ruby


group :development, :test do
  gem 'fume-dev', '~> 0.2.1'
end

group :doc do
  gem 'sdoc', require: false
end